Porting changes from r34872 to `SSBX`: Rebekah Hounsell reported on 03/26/2015 that `drizzlepac.tweakback` in SSBX crashes with `AttributeError: 'HSTWCS' object has no attribute 'calcFootprint'` because as of `v1.0 (2015-02-18)` Astropy has replaced `calcFootprint()` with `calc_footprint()`.
git-svn-id: http://svn.stsci.edu/svn/ssb/stsci_python/drizzlepac/branches/irafx@38480 fe389314-cf27-0410-b35b-8c050e845b92